travis:
  secure:
    BINSTAR_TOKEN: K7NtZ2/PNqa9LoJcA4AxsHFNZKF71mZthqxaTs75NlwzYToYcHet4wxGnJgYdIv9IbkSvhGsROHgDqACx6HQtKBflL6ACcDBVsz2c8o9yeBNDEppG2E2KQ2w8aWooZVKu+MbwnZN09g061fpC4P+snTeEgi1VTSdpGsx3OpwcDWj01bxAd9yODmFzWkgYffuIK0JOePfgXTM1NcrmMK9nrr5QS5pVMcxVbujZHiefNFpDXo7sty9Q1r91yw6AXVsRwoO/vSvtLpIFCfwkh2Q5SLOfs+FDsqbrOeWjuwa7bvdjwoh2zqABfVCW8OXNEugC/y2JGmcHN52NUAAj83uMjhwkiSfElpDUF9yIM1wmZxaGyvuFkcVH/m09TT1kW4vz8lrhhjNAYkvm4e8dGiZC3dLhX6ylwwQQRjiUKkvNwDirRCyEJsEqM+XOAZUsh2mOM5bt9qxlNQt3w0L57nTMgP8WKutU/q8391ypDsn92MJlN/lqV7evpvasa/zoagh3ICMCoeHYpqeiupDOosU0ePTdp3UWOv9w4rNxhPlfDNb4XuWiTXVDQrbbhs2NrJa0HXNBEHvn2pdzDU0fGAKS5C3/SFXN1q8BzAMYDTddGg3kkuEw0WZ+P8EvdhEKelg3tpEo48KEwcTyxbAVK/Ql1cVE0R1Fq4+YZNsLVXcqRw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
