travis:
  secure:
    BINSTAR_TOKEN: fk5ml2k17IWQ7nq/2rLvDpibow3Gg9/uY/kCO7p+JU7hsjF2Svf2zY8MBwQ7VIbwzCcBkWyZTaYNG1lxEw8dBZF0exINfT2lR3A/tEv4M7ep5SuJg85et3qbjjNoJkjOj4tVXX+po8HeqoOd7ti3TM6zOLNRfjRXiQVaJbFJwhbkKtKuRZfwDzmezdj+oYcc139n/Bp/SOiOfpJCQ79OHhAwNhNzttQJoQHunNbmjkYFBlNKbgS9LZ4D6DOgUhZn8QjtqmQ8DfYblB6gjkkmxN6V+yc7tHK2yNTXYjUP+cXk5k+d/5kEta6dTlJR23VLh21UGit/K1CJMGNlnYE3VbCccwFGCS9TbGoWUNI4x0f3Ya39REbblD0IyUdvLjfqVDDTL/7F1phGlt5PxcVyQ0rWdVrZDskC/6Z3z0TjWCVHlBj3QKGaCGZGAWQX6Y9c75D3Rg0zNSn59F3UrKqxMPsG5/CNhxPY9Dw/4I5aUq1NT2R+kLpW306EQ7D1ugn3T6ClkVqFgw0hyqIrQsnx2UTJ1cfacmdtEi0K4KYXPQ/anw5uItPmR5hclw79ACvcGMYZP97pulPyZwSFGZDecSPxUQ8d1KyGO3rKb+hl4iluXJ1tTlcS9CEvf0abKLH09WhkoYZl+Wdhi5x+9BINPM4tedSAkBLZXhqhMybtfhI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
