travis:
  secure:
    BINSTAR_TOKEN: JgabtFdfqTnSHnYkh413Cn5TF2UAqi3cJbpiorjtLTpp09Y0fl3Zz1a0IOTcyTpiFZYucuvTwtNqpwS/CqkPSCB2MvMinfLsQxOSJEM+J6x4FpCqY3QdkQoL3e2zXAwWrtWfEhtqquX3KwujCzFcHccLNPR+BnwiWKHGPjn5gVa1QukJeWr+qQoWEZT3rt6qlaU3+Gyjlw092PHuOxUZxU2/4JeD6UxWZLr3j4CwGj5Bl8R8bQbAi/si58fNzIXV5IYOVMrnmSJOWG/A9e5FuMlM3vN3iluIhs+rFeO/+zE4MXylNmxWerh3ScSoRyf/RqkV1nxf0B3ZqgH3uDKh/y3+7tG12kXmOcuxKjC2Ok4pxNVNHrL9Rfq12XwVcNhX0ufghx049XwzY42/YNH3LbYH1w64aZZstlM91GBRTIngmkknIsH3EZYlVl/ZPoa/l2WZxWzo7JdmtuRzpoeK/zCgtHW5ScafvzZHA1u2m8ZyvQSt9h75Z5JWOwF9PekIM77OZZzlAtA9ZiTe6/+J+GHSPUWAOhHctrTlQORk+QhtJsMlPjlKkJD5J22zLwranaaCINpqZP0650EtRWzTvq+d0ZE26/lZtMdSjuAphXSr/Gu2jOKdc/bG1KCr0rGdX5BcWk/cfNvKJ335agYohouBdTvKhCxkqJ3ZmXtWBbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
