travis:
  secure:
    BINSTAR_TOKEN: n7OAUQjSc7YUNZ76nyhyZKLkD4T/dDY7LXRC41rjL0GS4/2lSe/JD2UWP+txFvs+F4IA8yoOsQIx4XBurNUsja/xUDzywiB6zauAjQ+qjlCgArovlgvyBIAtGYhuYpGXvBXlZPabyUFrdZuoO8/wHtPfO7GtKeyaY+H2gEE5Ma6IbXXCTVmlLttwur7mL/oyRJPZmlqrkOoIvQwuoOhCv9Df4B9/xKcWmv97Lm/bg2dzfCOx2XnCMBiGQIk54HGJx2jBaF4YuEMVg165INd+E9TLTOqC6kGjqPiwqsf4KBhNhJab2P9BVMSyPEgmy+JbfTGhqNxx4BsUGGn2VfRHoAjx00rFahFuih6uM4EdVEFbPkySqqs4C3mVIibHIg2uKnf8NiQl83MObHE6IO5KUvlypRv05XnkfEIW9kI2sfYyKvgEY6BhBPCXySQsgb1mogOt9iACODUKY/1aVU9H4mpoeS1JO87jKLL1cMrTn/cwN2SNjyXTKEwV8yzTYKLfFJ7dUnAXFCczPdh1vft6TUzMDyRjkUHQWZzJTuvXt6TYZyzTm8oMXLadS74+UFMwUwz2uGNCDdYjv7TFalf+pxr2leK99+SMvKXP+5V1yYT8sBiZC9tQOiEi1+tpj2QIYchk4WAMAxb1LeUokZLDZ0CcHf1YMUHvQtG5gLmGtmE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
