travis:
  secure:
    BINSTAR_TOKEN: UQtMHa+3O0L9YU0hgrPeV7W5LJl1wilpNG13YaPXsH+Qu43J6WkW3z9PZS2hPcNrHJwsKNdvX7dvsz2W8io0YUkSEW0TmBrf29Uy/Beb2aeWtnc8k6dZ4TDK5NkcAoz2OuFMNuDmmK6ekkks39tfPXyWvO3OoN5G5QumYvGfteQLkawPALLY/bP38EkNSpYK3l9n3/qrrU7eSVvDekvoU2bC6t4gfTJCy2gM520sVZJCK45zdK55Qz0KdTg7P6O+t48WbkEnzjWxuRmukseLg1Yvrikol0OeRUqTmGKk2/r3L6GQXWZvGr6qf8/IgToUpzBmFVAm5Pdaeijk5+0p7Z2p1d66nfgen+9MgrqVS41WcTbA9kCLwYuTqxbJCNIvGnaK51syxJkiRShWMwoe5K7VFaWOoWe8B3h8lcxHci74OVNv6lRN3TESSzkTGywFvj3RXEfEfLLRaXGT0MRm6eNVLcU6O2205S9UgSPtWN9khx+FeDjxun3JcQHbfxYju+mYz4hHORh8eOcoBSETL+zFPCWD2IiHzx0thnJOyGUEbkrh/SFhF2lnLMovITfRDNHeEzKMj2nPnZHVFKioihMTE8uAkjZ6k3OoYr49peL6tq/E+yJWkraZWSR/1F264J1ua/h2690ODillpMTE8K5N4QQ3rxD+AcL/DOTTG7c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
